### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by Kuniwak** [Vimjas/vint#127]
I have maintained the vint for half a year, but I will be busy for the next half a year.
So I will be not able to maintain constantly.

If you interest in the Vint, please help to make Vint better.
- [Design diagram](https://github.com/Kuniwak/vint/wiki/Vint-design)
##### EDIT

I mean that "I'm going to continue to maintain Vint, but now I need more help."

**Comment by nateozem** [comment]
I wouldn't mind helping. What is the best way to contact you for questions?

**Comment by Kuniwak** [comment]
Sorry for my late reply.

Please contact me via email.
My email address is `orga.chem.job+github@gmail.com`.

**Comment by Kuniwak** [comment]
@Coacher This project want some co-maintainers. Are you interesteed?
If you interest it, I'm gonna give you write-access permission.

**Comment by Coacher** [comment]
@Kuniwak, thanks. I'm interested to see this project alive. I cannot help much with new features, but I can work on fixes (starting with trivial ones). Let's do it :)

**Comment by Kuniwak** [comment]
@blueyed I'm sorry for my less activity on this project. Currently I do not spent much time for Vint, so I want some co-maintainers.  Are you interesteed?
If you interest it, I'm gonna give you write-access permission.

**Comment by blueyed** [comment]
@Kuniwak 
Sure, this is a great project.
Thanks for all your work so far!

**Comment by blueyed** [comment]
@Kuniwak 
btw: I would be nice to document the release process, and maybe even configure Travis to do it based on tags.  For reference: https://github.com/pytest-dev/pytest-django/blob/8bd3d3ea058fbe337db69d8c0256b995351b4161/.travis.yml#L37-L49.
This means that you should either give me access to PyPI also (not really necessary), or then provide the "travis encrypt" for your account.

**Comment by Kuniwak** [comment]
Thanks! I've invited you as repository collaborator and PyPI maintainer.

**Comment by blueyed** [comment]
Closing.  Thanks again for all your work here already! \o/
