### ISSUE TITLE
Incorrect E477

### ISSUE THREAD

**Issue by paretje** [Vimjas/vint#163]
In a function in my vimrc, I use `Gdiff!`. Without any extra arguments, vint returns:

```
.vimrc:588:3: E477: No ! allowed (see ynkdir/vim-vimlparser)
```

**Comment by paretje** [comment]
I opened an issue at [vim-vimlparser](https://github.com/ynkdir/vim-vimlparser/issues/20).

**Comment by blueyed** [comment]
Pending fix in https://github.com/ynkdir/vim-vimlparser/pull/28.

**Comment by tyru** [comment]
this was already fixed.

**Comment by blueyed** [comment]
Thanks, @tyru.
Let me know if you'd like to be added as contributor etc so that you can close issues yourself.

**Comment by tyru** [comment]
I want to be a contributor because I can close issue, judge the cause is vimlparser, delegate to vimlparser issue, and so on.
