### ISSUE TITLE
#177 breaks pip install for python2

### ISSUE THREAD

**Issue by gregorias** [Vimjas/vint#182]
Issuing `pip install vim-vint` results in an error: 

```
Complete output from command python setup.py egg_info:
error in vim-vint setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

Using pip3 or specifying vim-vint=0.3.9 installs vim-vint correctly.

I can't find any documentation on `~=`, which suggests that this is the culprit.

**Comment by Kuniwak** [comment]
Thanks for reporting.

I found the the operator `~=` on [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release).

I want to know your environment in more detail:

- OS
- Python version
- pip version

**Comment by gregorias** [comment]
The OS is Linux Mint 17.3 Rosa 64-bit.

Tested combinations of python and pip on which I get that error are:
pip 1.5.4 (python2.7)
pip 8.1.2 (python2.7)

Note that I'm not 100% sure that it's the requirements,txt file that's causing this. I blame it, because of the error string and the temporal and semantic closeness of the change to that file.

**Comment by gregorias** [comment]
Let me know if you need further help on this issue. If you can't reproduce, perhaps I can debug this more thoroughly.

**Comment by gregorias** [comment]
The error has disappeared and vint installs successfully. after I have updated my system from Linux Mint 17.3 to 18.  The new python2 version is 2.7.12, pip's version is pip 8.1.1.

I would consider it an issue with older python2 versions.

**Comment by dezza** [comment]
On WSL I have the same error with both python2 and python3 pip

```sh
$ pip3 -V
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
$ sudo pip3 install vim-vint
Downloading/unpacking vim-vint
  Downloading vim-vint-0.3.11.tar.gz (61kB): 61kB downloaded
  Running setup.py (path:/tmp/pip_build_root/vim-vint/setup.py) egg_info for package vim-vint
    error in vim-vint setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in vim-vint setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/vim-vint
Storing debug log for failure in /home/dza/.pip/pip.log
$ sudo pip install vim-vint
Downloading/unpacking vim-vint
  Downloading vim-vint-0.3.11.tar.gz (61kB): 61kB downloaded
  Running setup.py (path:/tmp/pip_build_root/vim-vint/setup.py) egg_info for package vim-vint
    error in vim-vint setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in vim-vint setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/vim-vint
Storing debug log for failure in /home/dza/.pip/pip.log
```

**Comment by Kuniwak** [comment]
@dezza this issue is probably caused by legacy Python2.
Could you update to newer Python2?

**Comment by gregorias** [comment]
Python 2 is no longer supported, so I think we can close this issue.
