### ISSUE TITLE
Setup PyPI deployment through Travis

### ISSUE THREAD

**Issue by blueyed** [Vimjas/vint#315]

**Comment by jayvdb** [comment]
Sort of relevant here, https://pypi.org/project/vim-vint/ has a 0.3.21, but https://github.com/Kuniwak/vint/releases does not.

**Comment by blueyed** [comment]
@jayvdb 
Pushed the missing tag, thanks.

**Comment by blueyed** [comment]
Released https://pypi.org/project/vim-vint/0.4a3/ via it.. \o/
