### ISSUE TITLE
Vint erroneously marks default values for function arguments as errors

### ISSUE THREAD

**Issue by jmdevin** [Vimjas/vint#337]
### The Problem
The following function is valid vimscript. Vint, however, marks the equals sign an "unexpected token."
```vimscript
function! TestFunction(test = 1) abort
    echo a:test
endfunction
```
```
$ vint test.vim
test.vim:1:29: unexpected token: = (see vim-jp/vim-vimlparser)
Total violations: 1
```

### Reproduce
1. Create a file called test.vim
2. Add the following lines to the file:
```vimscript
function! TestFunction(test = 1) abort
    echo a:test
endfunction
```
3. Optionally, source the file and run `:call TestFunction()` and `:call TestFunction(267)` to see that the function works.
4. Exit vim
5. Run `vint test.vim` on your command line and see vint return an error incorrectly.

I took a quick look but I didn't see that this had been reported before.

**Comment by blueyed** [comment]
Thanks for the report.
It is not supported yet.
I've created https://github.com/vim-jp/vim-vimlparser/issues/154.

**Comment by jdhao** [comment]
The pypi version of vint is way too old. So it still complains the false positive error about default value for positional arugment.
 Is there any plan to update that version?
