### ISSUE TITLE
Support for [new] .. string concatenation operator in v0.4a1

### ISSUE THREAD

**Issue by LumaKernel** [Vimjas/vint#338]
I'm using vint on Windows so I need `v0.4a1` ( #290 ) but the parser in this version is still old. ( #306 )
I want pre-release new version for now.

**Comment by blueyed** [comment]
Would be easier with / should be done after https://github.com/Kuniwak/vint/issues/315.

I suggest installing/using master for now.

**Comment by blueyed** [comment]
https://pypi.org/project/vim-vint/0.4a3/ has been released now.
