### ISSUE TITLE
Transfer repo to https://github.com/Vimjas/ ?

### ISSUE THREAD

**Issue by blueyed** [Vimjas/vint#350]
I've thought about this before, and am running into an issue with "travis encrypt" (for #315, https://github.com/travis-ci/travis.rb/issues/687, https://travis-ci.community/t/travis-encrypt-data-too-large-for-pypi-tokens-with-older-repos/5792/4).
Instead of using a workaround (two env vars) I've thought that moving it to a new org would be a better workaround (it should create a new (bigger) key then).

@Kuniwak 
What do you think?

**Comment by Kuniwak** [comment]
@blueyed Basically, I strongly agree that move Kuniwak/vint to <new org>/vint if it is you meant. 

I think there are 2 approaches:

1. creating new org like `github.com/vim-vint`

    `github.com/vint` is a better org name, but it is in used. `vim-vint` is not used yet now, and this name is same as the name in PyPI.

2. using an org like `github.com/Vimjas` or others

    But I don't know about Vimjas... I think Vimjas is good choice if the org is mainly related to vim and the org is opened to community.

What do you think about these approaches?

**Comment by blueyed** [comment]
@Kuniwak 
I've created the Vimjas org myself to host Vim projects, and everybody is welcome to join.. :)
So I'd like to go with that (2nd option).

**Comment by Kuniwak** [comment]
@blueyed 
Sounds good. I agree that move to Vimjas. Does you have permission to transfer the repo?

**Comment by blueyed** [comment]
@Kuniwak 
Cool.
No, I don't see "settings" here.
I assume you want to join Vimjas - I'll invite you there then, so you can do the transfer, ok?

**Comment by Kuniwak** [comment]
@blueyed 

I tried to transfer, but it failed because I didn't have the permission to create repo on Vimjas.

Would you invite me to Vimjas to get the permission?

**Comment by blueyed** [comment]
@Kuniwak 
I've sent the invitation already.

**Comment by Kuniwak** [comment]
Ah, I've missed it. I'm gonna retry.

**Comment by blueyed** [comment]
\o/
Thank you!

**Comment by blueyed** [comment]
Unfortunately "travis encrypt" still fails.. :/
