### ISSUE TITLE
Method calls reported as errors

### ISSUE THREAD

**Issue by ipkiss42** [Vimjas/vint#357]
Vint version: 0.4a4.dev5+gfb6fa16

In the following snippet, Vint shows an error: `E488: Trailing characters: - (see vim-jp/vim-vimlparser)`

```vim
let s = "   a"->trim()
```

However this code is valid, see `:h method` for details (or run it interactively and print the value of `s`).

**Comment by blueyed** [comment]
Yeah, that's not supported/parsed yet.
Ref: https://github.com/vim-jp/vim-vimlparser/issues/150
