### ISSUE TITLE
False error for optional function argument

### ISSUE THREAD

**Issue by rottencandy** [Vimjas/vint#383]
Vint gives an error for optional arguments in functions.
For the example from `:h optional-function-argument`:
```vim
function Something(key, value = 10)
   echo a:key .. ": " .. a:value
endfunction
```
Error:
```sh
test.vim:1:31: unexpected token: = (see vim-jp/vim-vimlparser)
```

**Comment by infinitewhileloop** [comment]
I encountered the same bug. Optional function arguments have been supported since [Vim  8.1.1310](https://github.com/vim/vim/commit/42ae78cfff171fbd7412306083fe200245d7a7a6).

**Comment by rottencandy** [comment]
@infinitewhileloop thank you! Installing the git version does solve the issue!
